//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolrCollection) DeepCopyInto(out *SolrCollection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolrCollection.
func (in *SolrCollection) DeepCopy() *SolrCollection {
	if in == nil {
		return nil
	}
	out := new(SolrCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolrCollectionList) DeepCopyInto(out *SolrCollectionList) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SolrCollection, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolrCollectionList.
func (in *SolrCollectionList) DeepCopy() *SolrCollectionList {
	if in == nil {
		return nil
	}
	out := new(SolrCollectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolrCollectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolrCollectionSet) DeepCopyInto(out *SolrCollectionSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolrCollectionSet.
func (in *SolrCollectionSet) DeepCopy() *SolrCollectionSet {
	if in == nil {
		return nil
	}
	out := new(SolrCollectionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolrCollectionSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolrCollectionSetList) DeepCopyInto(out *SolrCollectionSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SolrCollectionSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolrCollectionSetList.
func (in *SolrCollectionSetList) DeepCopy() *SolrCollectionSetList {
	if in == nil {
		return nil
	}
	out := new(SolrCollectionSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolrCollectionSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolrCollectionSetSpec) DeepCopyInto(out *SolrCollectionSetSpec) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(int32)
		**out = **in
	}
	if in.BlueGreenEnabled != nil {
		in, out := &in.BlueGreenEnabled, &out.BlueGreenEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CleanupEnabled != nil {
		in, out := &in.CleanupEnabled, &out.CleanupEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Collections != nil {
		in, out := &in.Collections, &out.Collections
		*out = make([]SolrCollection, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolrCollectionSetSpec.
func (in *SolrCollectionSetSpec) DeepCopy() *SolrCollectionSetSpec {
	if in == nil {
		return nil
	}
	out := new(SolrCollectionSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolrCollectionSetStatus) DeepCopyInto(out *SolrCollectionSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SolrCollections != nil {
		in, out := &in.SolrCollections, &out.SolrCollections
		*out = make([]SolrCollectionStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolrCollectionSetStatus.
func (in *SolrCollectionSetStatus) DeepCopy() *SolrCollectionSetStatus {
	if in == nil {
		return nil
	}
	out := new(SolrCollectionSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolrCollectionStatus) DeepCopyInto(out *SolrCollectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolrCollectionStatus.
func (in *SolrCollectionStatus) DeepCopy() *SolrCollectionStatus {
	if in == nil {
		return nil
	}
	out := new(SolrCollectionStatus)
	in.DeepCopyInto(out)
	return out
}
