apiVersion: v2
name: solr-collections-operator
description: A Helm chart to distribute solr-collections-operator
type: application

version: 1.3.1
appVersion: 1.3.1

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
